# Generated by Django 4.2.5 on 2023-09-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
