# Generated by Django 4.2.5 on 2023-10-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='image',
        ),
    ]
